/**
 * Numerical parity: `runTwoWayAnova` must reproduce omicViz's ACTUAL two-way
 * implementation. Fixtures are generated by running omicViz's
 * _run_two_way_anova + _finalise on synthetic standardized data (same raw input
 * fed to both), covering the symmetric (strain×time) and asymmetric
 * (cmpd×strain, vehicle dose-excluded) code paths. stat_type = pP.
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import Papa from 'papaparse'
import { describe, expect, it } from 'vitest'

import { runTwoWayAnova, type TwoWayFactor } from './twoWay'
import { DEFAULT_THRESHOLD } from './stats'
import type { CompareResultRow, ConditionKey, Pair, StandardRow } from './types'

const here = dirname(fileURLToPath(import.meta.url))
const fx = (name: string): string => readFileSync(join(here, '__fixtures__', name), 'utf8')

type Rec = Record<string, string>

function toRows(csv: string): StandardRow[] {
  const recs = Papa.parse<Rec>(csv, { header: true, skipEmptyLines: true }).data.filter(
    (r) => r.uniqID
  )
  return recs.map((r) => ({
    uniqID: r.uniqID,
    strain: r.strain ?? '',
    cmpd: r.cmpd ?? '',
    dose: r.dose !== undefined ? Number(r.dose) : null,
    time: r.time !== undefined ? Number(r.time) : null,
    rep: Number(r.rep),
    value: Number(r.value)
  }))
}

interface ExpectedRow {
  uniqID: string
  log2FC: string
  pP: string
  pQ: string
  signf: string
}

function checkParity(
  inputFile: string,
  expectedFile: string,
  factors: [TwoWayFactor, TwoWayFactor],
  active: ConditionKey[]
): void {
  const res = runTwoWayAnova({
    rows: toRows(fx(inputFile)),
    factors,
    activeConditions: active,
    threshold: { ...DEFAULT_THRESHOLD, statType: 'pP' }
  })
  const expected = Papa.parse<ExpectedRow>(fx(expectedFile), {
    header: true,
    skipEmptyLines: true
  }).data.filter((r) => r.uniqID)

  const actual = new Map<string, CompareResultRow>(res.rows.map((r) => [r.uniqID, r]))

  expect(expected.every((e) => actual.has(e.uniqID)), 'all expected genes present').toBe(true)
  expect(res.rows.length).toBe(expected.length)

  for (const e of expected) {
    const a = actual.get(e.uniqID)!
    const near = (got: number | null, want: string, field: string): void => {
      if (want.trim() === '') return
      const w = Number(want)
      if (!Number.isFinite(w)) return
      expect(got, `${field} @ ${e.uniqID}`).not.toBeNull()
      expect(Math.abs((got as number) - w), `${field} @ ${e.uniqID}`).toBeLessThan(1e-6)
    }
    near(a.log2FC, e.log2FC, 'log2FC')
    near(a.pP, e.pP, 'pP')
    near(a.pQ, e.pQ, 'pQ')
    expect(a.signf, `signf @ ${e.uniqID}`).toBe(e.signf.toLowerCase() === 'true')
  }
}

const p = (n: string, d: string): Pair => [n, d]

describe('two_way_anova parity vs omicViz', () => {
  it('symmetric strain × time', () => {
    checkParity(
      'twoway_sym_input.csv',
      'expected_twoway_sym.csv',
      [
        { condition: 'strain', pairs: [p('M', 'W')] },
        { condition: 'time', pairs: [p('1', '2')] }
      ],
      ['strain', 'time']
    )
  })

  it('asymmetric cmpd × strain (vehicle dose-excluded)', () => {
    checkParity(
      'twoway_asym_input.csv',
      'expected_twoway_asym.csv',
      [
        { condition: 'cmpd', pairs: [p('E28', 'DMSO')] },
        { condition: 'strain', pairs: [p('M', 'W')] }
      ],
      ['cmpd', 'strain', 'dose']
    )
  })
})
