import { join } from 'path'
import { existsSync } from 'fs'
import { BrowserWindow, shell } from 'electron'
import { WINDOW_PRESETS, type WindowPresetName } from './window-presets'

// Single-source-of-truth master icon. Used for the dev window on Win/Linux
// (macOS dev shows the default Electron dock icon; packaged apps use the .icns
// generated by electron-builder from this same file).
const ICON_PATH = join(__dirname, '../../build-resources/icon.png')

/** Per-window overrides applied on top of a preset's defaults. */
export interface CreateWindowOptions {
  /** Query string appended to the renderer URL, e.g. "?preset=square-1-1". */
  search?: string
}

/**
 * Create a BrowserWindow sized and constrained by a named preset.
 * This is the single entry point every OneProduction app uses to open a window.
 */
export function createWindowFromPreset(
  name: WindowPresetName,
  options: CreateWindowOptions = {}
): BrowserWindow {
  const preset = WINDOW_PRESETS[name]
  if (!preset) throw new Error(`Unknown window preset: ${name}`)

  const win = new BrowserWindow({
    width: preset.width,
    height: preset.height,
    minWidth: preset.minWidth,
    minHeight: preset.minHeight,
    show: false,
    autoHideMenuBar: true,
    ...(existsSync(ICON_PATH) ? { icon: ICON_PATH } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'), // CJS preload (main/preload build as CommonJS)
      sandbox: false,
      contextIsolation: true
    }
  })

  if (preset.lock) {
    win.setAspectRatio(preset.aspectRatio)
  }

  win.once('ready-to-show', () => win.show())

  win.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  loadRenderer(win, options.search)
  return win
}

function loadRenderer(win: BrowserWindow, search = ''): void {
  // electron-vite exposes the dev server URL via this env var; falls back to the
  // built HTML file in production.
  const devUrl = process.env['ELECTRON_RENDERER_URL']
  if (devUrl) {
    win.loadURL(devUrl + search)
  } else {
    win.loadFile(join(__dirname, '../renderer/index.html'), {
      search: search.replace(/^\?/, '')
    })
  }
}
